# Messages for Bavarian (Boarisch)
# Exported from translatewiki.net
# Export driver: syck-pecl
# Author: Mucalexx
bar: 
  account_information: Nuterkontóinformaziónen
  account_registered_but_not_ready_try_later: Eaner Konto is registriard ower no ned zum orweiten bereit. Bittschee vasuachen S' as in fymf Minuten noamoi.
  activerecord: 
    attributes: 
      content_page: 
        active: Vaéffmtlichung
        page_name: Eihdeitiger Naum
        sort_order: Sortierreinfóing
      content_partner: 
        acronym: Prójektobkyrzung
        admin_notes: Administraaziónshihweis
        auto_publish: Autómaatisch vaéffmtlichen
        content_partner_status: Prójektstaatus
        created_at: Erstejd
        description: Prójektbschreiwung
        display_name: Auhzoagnaum
        full_name: Prójektnaum
        homepage: Prójekt-URL
        id: Kénnung
        notes: Prójektnótiezen
        public: Éffmtlich
        resources: Quejn
        user_id: Vawoitt voh
        vetted: Priafft
    models: 
      user: Kóntó
  add_to_my_collection_button: Zua da meining Såmmlung dazuadoa
  admin: Administrator
  cancel: obbrecher
  change_rating_to_2_of_5: Bewertung auf 2 vo 5 ändern
  common_names_with_count: 
    one: "%{count} gebreichliche Bezeichnung"
    other: "%{count} gebreichliche Bezeichnungen"
  communities: Gmoaschoften
  communities_with_count: 
    one: Oah Gmoahschoft
    other: "%{count} Gmoahschoften"
  community_activity: Aktivität vo derer Gmoaschoft
  content_summary_introduction_html: De foigernden Wertt stön d'Summe vo de vaschiadanen Inhoitstypm fyr de Taxon midsåmt olle vo iare untergordneten Elemente dor. %{glossary_term_trusted} D' Inhoite san entweeder voram Kurator auf EOL gneemigt worn, oder ståmmern voram vatraunswyrding Daatenliaferrant. %{glossary_term_unreviewed} D' Inhoite san bislång ned voram Kurator auf EOL bewertt worn. Jeeder taxonomische Hiararchie is eizigortig, sodaas a jeede durchsuachbore Hiararchie z' Vagleichen is.
  content_summary_table_count_column_header: Åzoi
  could_not_find_user: Zua dem Nutzer do is koa Midgliadsschoft in ner Gmoaschoft gfunden worn.
  curators_summary_header_with_count: 
    one: "%{count} Kurator"
    other: "%{count} Kuratorn"
  delete_community: De Gmoaschoft do leschen
  donation_error_only_numbers: Bittscheh gib a Menge netter mid da Hüf voh Ziffern å.
  edit_community: Gmoaschoft beorweiten
  edit_my_profile: Eaner Profü beorweiten
  filter_by_status: Noch Staatus füjtern
  filter_by_status_all_option: olle Staatuse
  filter_by_type_all_option: olle Typm
  filtered_information: Gfüterde Informazionen
  global_access_tagline: Wödweider Zuagång zum Wissen ywers Leem auf da Erden.
  help: Hüfe
  home: Startseiten
  home_page_link_advisory_information: Der Link do bringt de zur Hauptseiten vo da Enzyklopädie vom Leem.
  images: Büder
  images_with_count: 
    one: "%{count} Bild"
    other: "%{count} Büder"
  last_updated_time_ago: As letzte moi vur %{time_passed} aktualisiard
  learn_about_content_partners: Erforn S' merer ywer unserne Partner fyr Inhoite
  license: Lizenz
  license_cc_by_2_0: Creative Commons „Nåmensnennung“ 2.0 (CC BY 2.0)
  license_cc_by_nc_3_0: Creative Commons „Nåmensnennung, ned kommerziö“ 3.0 (CC BY-NC 3.0)
  license_cc_by_nc_sa_3_0: Creative Commons „Nåmernsnennung, ned kommerziö, Weidergob unter gleiche Bedingungen“ 3.0 (CC BY-NC-SA 3.0)
  license_cc_by_sa_2_0: Creative Commons „Nåmensnennung, Weidergob unter gleiche Bedingungen“ 2.0 (CC BY-SA 2.0)
  license_cc_by_sa_2_5: Creative Commons „Nåmensnennung, Weidergob unter gleiche Bedingungen“ 2.5 (CC BY-SA 2.5)
  license_gnu_gpl: GNU General Public License (GNU GPL)
  location: Ståndort
  login_or_create_account: Åmöden oder Nutzerkonto erstön
  media: Medien
  minimal_page: Minimaale Seiten
  must_be_associated_with_either_a_user_or_a_community: Muass entweeder am Nutzer oder ner Gmoaschoft zuagordnet sei.
  my_activity: De meining Aktivitäten
  my_info: Meine Informazionen
  pages_with_pictures_and_text: Seiten mid Büder und Text
  personal_space: Perseenlicher Bereich
  post_comment: Kommentiarn
  remove_membership: Gmoaschoftszuagherigkeid beenden
  resources: Informaziónsquöner
  rights_holder: Rechteinhower
  show_status_message: Staatusmödung åzoang
  source_url: Quön-URL
  text_summary_more_link: An voistending Eitrog leesen
  text_with_count: 
    one: "%{count} Artike"
    other: "%{count} Artike"
  there_are_currently_no_members_in_this_community: De Gmoaschoft hod im Moment koane Midgliader ned.
  twitter: Twitter
  unreviewed: Ned priafft
  what_is_eol: Wos is 'n EOL ywerhaupt?
  what_is_this_question: Wos bedeitt dés?
  you_are_not_authorized_to_perform_this_action: Se san ned berechtigt, de Akzion do durchzfyrn.
  your_current_rating_2_of_5: "Deih derzeidige Bewertung: 2 von 5"
  your_rating: Eaner Bewertung
