# Messages for Bosnian (Bosanski)
# Exported from translatewiki.net
# Export driver: syck-pecl
# Author: Palapa
bs: 
  communities: Zajednice
  edit_my_profile: Uredi moj profil
  help: Pomoć
  images: Slike
  learn_about_content_partners: Saznajte o našim sadržajnim partnerima
  location: Lokacija
  punctuation_comma: ","
  resources: Resursi
  twitter: Twitter
  you_are_not_authorized_to_perform_this_action: Niste ovlašteni da obavite ovu radnju.
  your_rating: Vaša procjena
