# Messages for Esperanto (Esperanto)
# Exported from translatewiki.net
# Export driver: syck-pecl
# Author: Happy5214
# Author: Objectivesea
eo: 
  translated_activities-name-activity_id-19: profilo
  translated_activities-name-activity_id-50: nefidata
  translated_activities-name-activity_id-51: montri
  translated_activities-name-activity_id-52: krei
  translated_activities-name-activity_id-53: kaŝi
  translated_activities-name-activity_id-54: ĝisdatigi
  translated_activities-name-activity_id-55: netaŭga
  translated_activities-name-activity_id-56: forigi
  translated_activities-name-activity_id-58: fidata
  translated_activities-name-activity_id-59: nerevizita
  translated_activities-name-activity_id-63: kolekti
  translated_activities-name-activity_id-64: forigi
  translated_agent_roles-label-agent_role_id-1: Animisto
  translated_agent_roles-label-agent_role_id-10: Projekto
  translated_agent_roles-label-agent_role_id-11: Eldonejo
  translated_agent_roles-label-agent_role_id-12: Registristo
  translated_agent_roles-label-agent_role_id-13: Fonto
  translated_agent_roles-label-agent_role_id-14: Fonta datenbazo
  translated_agent_roles-label-agent_role_id-16: Kontribuanto
  translated_agent_roles-label-agent_role_id-2: Aŭtoro
  translated_agent_roles-label-agent_role_id-21: provizanto
  translated_agent_roles-label-agent_role_id-22: Tradukanto
  translated_agent_roles-label-agent_role_id-23: Scienca revizianto
  translated_agent_roles-label-agent_role_id-24: Lingvistika revizianto
  translated_agent_roles-label-agent_role_id-3: Kompilanto
  translated_agent_roles-label-agent_role_id-4: Komponisto
  translated_agent_roles-label-agent_role_id-5: Kreinto
  translated_agent_roles-label-agent_role_id-6: Direktoro
  translated_agent_roles-label-agent_role_id-7: Redaktoro
  translated_agent_roles-label-agent_role_id-8: Ilustristo
  translated_agent_roles-label-agent_role_id-9: Fotografisto
  translated_audiences-label-audience_id-1: Spertuzantoj
  translated_audiences-label-audience_id-3: Infanoj
  translated_collection_types-label-collection_type_id-1: Taksonomio
  translated_collection_types-label-collection_type_id-10: Sonaĵoj
  translated_collection_types-label-collection_type_id-11: Ligiloj
  translated_collection_types-label-collection_type_id-12: Literaturo
  translated_collection_types-label-collection_type_id-13: Taksonomio
  translated_collection_types-label-collection_type_id-14: Molekulaj strikodoj
  translated_collection_types-label-collection_type_id-15: Priskribo
  translated_collection_types-label-collection_type_id-16: Bildoj
  translated_collection_types-label-collection_type_id-18: Stato de konservo
  translated_collection_types-label-collection_type_id-2: Molekulaj strikodoj
  translated_collection_types-label-collection_type_id-20: Molekula dateno
  translated_collection_types-label-collection_type_id-21: Nomenklaturo
  translated_collection_types-label-collection_type_id-22: Sonaĵoj
  translated_collection_types-label-collection_type_id-23: Ligiloj
  translated_collection_types-label-collection_type_id-24: Literaturo
  translated_collection_types-label-collection_type_id-3: Priskribo
  translated_collection_types-label-collection_type_id-4: Bildoj
  translated_collection_types-label-collection_type_id-5: Distribuo
  translated_collection_types-label-collection_type_id-6: Stato de konservo
  translated_collection_types-label-collection_type_id-8: Molekula dateno
  translated_collection_types-label-collection_type_id-9: Nomenklaturo
  translated_content_partner_statuses-label-content_partner_status_id-1: Okazonta
  translated_content_partner_statuses-label-content_partner_status_id-2: Aktiva
  translated_content_partner_statuses-label-content_partner_status_id-4: Malaktiva
  translated_content_tables-label-content_table_id-1: Detaloj
  translated_data_types-label-data_type_id-1: Bildo
  translated_data_types-label-data_type_id-10: Mapo
  translated_data_types-label-data_type_id-2: Sonaĵo
  translated_data_types-label-data_type_id-3: Teksto
  translated_data_types-label-data_type_id-4: Vidaĵo
  translated_data_types-label-data_type_id-5: Bildo GBIF
  translated_data_types-label-data_type_id-6: IUCN
  translated_data_types-label-data_type_id-7: Flash
  translated_data_types-label-data_type_id-8: YouTube
  translated_licenses-description-license_id-1: Neniuj rajtoj rezervitaj
  translated_licenses-description-license_id-2: "&#169; Ĉiuj rajtoj rezervitaj"
  translated_licenses-description-license_id-29: Iuj rajtoj rezervitaj
  translated_licenses-description-license_id-3: Iuj rajtoj rezervitaj
  translated_licenses-description-license_id-30: Iuj rajtoj rezervitaj
  translated_licenses-description-license_id-31: Iuj rajtoj rezervitaj
  translated_licenses-description-license_id-32: Iuj rajtoj rezervitaj
  translated_licenses-description-license_id-33: Iuj rajtoj rezervitaj
  translated_licenses-description-license_id-34: Publika Domajno
  translated_licenses-description-license_id-35: Publika Domajno
  translated_licenses-description-license_id-36: Iuj rajtoj rezervitaj
  translated_licenses-description-license_id-37: Iuj rajtoj rezervitaj
  translated_licenses-description-license_id-38: Iuj rajtoj rezervitaj
  translated_licenses-description-license_id-39: Publika Domajno
  translated_licenses-description-license_id-4: Iuj rajtoj rezervitaj
  translated_licenses-description-license_id-42: Iuj rajtoj rezervitaj
  translated_licenses-description-license_id-5: Iuj rajtoj rezervitaj
  translated_licenses-description-license_id-6: Iuj rajtoj rezervitaj
  translated_licenses-description-license_id-7: Iuj rajtoj rezervitaj
  translated_licenses-description-license_id-8: Iuj rajtoj rezervitaj
  translated_licenses-description-license_id-9: Iuj rajtoj rezervitaj
  translated_ranks-label-rank_id-112: gen
  translated_ranks-label-rank_id-113: gen.
  translated_ranks-label-rank_id-118: genro
  translated_ranks-label-rank_id-169: infraordo
  translated_ranks-label-rank_id-175: infraspecio
  translated_ranks-label-rank_id-183: regno
  translated_ranks-label-rank_id-266: ordo
  translated_ranks-label-rank_id-280: filumo
  translated_ranks-label-rank_id-313: sekc
  translated_ranks-label-rank_id-314: sekc.
  translated_ranks-label-rank_id-317: sekcio
  translated_ranks-label-rank_id-324: serio
  translated_ranks-label-rank_id-332: SP
  translated_ranks-label-rank_id-333: sp.
  translated_ranks-label-rank_id-335: specio
  translated_ranks-label-rank_id-352: subfamilio
  translated_ranks-label-rank_id-370: subklaso
  translated_ranks-label-rank_id-375: subdivizio
  translated_ranks-label-rank_id-383: subfamilio
  translated_ranks-label-rank_id-390: subgen
  translated_ranks-label-rank_id-391: subgen.
  translated_ranks-label-rank_id-394: subgenro
  translated_ranks-label-rank_id-396: subregno
  translated_ranks-label-rank_id-399: subordo
  translated_ranks-label-rank_id-401: subfilumo
  translated_ranks-label-rank_id-408: subsekcio
  translated_ranks-label-rank_id-411: subserio
  translated_ranks-label-rank_id-413: subsp
  translated_ranks-label-rank_id-414: subsp.
  translated_ranks-label-rank_id-415: subspecio
  translated_ranks-label-rank_id-422: subtribo
  translated_ranks-label-rank_id-463: superfamilio
  translated_ranks-label-rank_id-472: superfilumo
  translated_ranks-label-rank_id-494: tribo
  translated_ranks-label-rank_id-51: klaso
  translated_ranks-label-rank_id-512: var
  translated_ranks-label-rank_id-513: var.
  translated_ranks-label-rank_id-517: vario
  translated_ranks-label-rank_id-518: vario
  translated_ranks-label-rank_id-562: notogenro
  translated_ranks-label-rank_id-563: notospecio
  translated_ranks-label-rank_id-564: notosubspecio
  translated_ranks-label-rank_id-565: notovario
  translated_ranks-label-rank_id-74: divizio
  translated_ranks-label-rank_id-85: f
  translated_ranks-label-rank_id-86: f.
  translated_ranks-label-rank_id-91: fam
  translated_ranks-label-rank_id-92: fam.
  translated_ranks-label-rank_id-99: familio
  translated_resource_statuses-label-resource_status_id-1: Alŝutanta
  translated_resource_statuses-label-resource_status_id-11: Eldonadon okazontas
  translated_resource_statuses-label-resource_status_id-12: Neeldonadon okazontas
  translated_resource_statuses-label-resource_status_id-2: Alŝutita
  translated_service_types-label-service_type_id-2: Alia
  translated_sort_styles-name-sort_style_id-2: Plej malnova
  translated_sort_styles-name-sort_style_id-5: Riĉeco
  translated_statuses-label-status_id-2: Ĝisdatigita
  translated_statuses-label-status_id-3: Neŝanĝita
  translated_synonym_relations-label-synonym_relation_id-1: sinonimo
  translated_synonym_relations-label-synonym_relation_id-13: misnomo
  translated_synonym_relations-label-synonym_relation_id-14: misliterumo
  translated_synonym_relations-label-synonym_relation_id-15: teleomorfo
  translated_synonym_relations-label-synonym_relation_id-16: ambigua sinonimo
  translated_synonym_relations-label-synonym_relation_id-17: misalfiksita nomo
  translated_synonym_relations-label-synonym_relation_id-18: provizore akceptita nomo
  translated_synonym_relations-label-synonym_relation_id-19: akceptita nomo
  translated_synonym_relations-label-synonym_relation_id-2: komuna nomo
  translated_synonym_relations-label-synonym_relation_id-22: ortografia varianto (misliterumo)
  translated_synonym_relations-label-synonym_relation_id-23: misalfiksita
  translated_synonym_relations-label-synonym_relation_id-24: malakceptita nomo
  translated_synonym_relations-label-synonym_relation_id-25: homonimo (mallica)
  translated_synonym_relations-label-synonym_relation_id-26: parte
  translated_synonym_relations-label-synonym_relation_id-27: superflua renomaĵo (mallica)
  translated_synonym_relations-label-synonym_relation_id-28: nomen oblitum
  translated_synonym_relations-label-synonym_relation_id-29: plijuna sinonimo
  translated_synonym_relations-label-synonym_relation_id-3: akronimo
  translated_synonym_relations-label-synonym_relation_id-30: nehavebla, datenbaza artefakto
  translated_synonym_relations-label-synonym_relation_id-31: senbezona remeto
  translated_synonym_relations-label-synonym_relation_id-34: originalnomo/kombinaĵo
  translated_synonym_relations-label-synonym_relation_id-35: nehavebla, erara unua literumo
  translated_synonym_relations-label-synonym_relation_id-36: plijuna homonimo
  translated_synonym_relations-label-synonym_relation_id-37: homonimo kaj plijuna sinonimo
  translated_synonym_relations-label-synonym_relation_id-4: anamorfo
  translated_synonym_relations-label-synonym_relation_id-40: nehavebla, alia kialo
  translated_synonym_relations-label-synonym_relation_id-41: nehavebla, nomen nudum
  translated_synonym_relations-label-synonym_relation_id-42: nomen dubium
  translated_synonym_relations-label-synonym_relation_id-46: sinonimo heterotipa
  translated_synonym_relations-label-synonym_relation_id-47: sinonimo homotipa
  translated_synonym_relations-label-synonym_relation_id-48: nehavebla nomo
  translated_synonym_relations-label-synonym_relation_id-49: valida nomo
  translated_synonym_relations-label-synonym_relation_id-50: valida
  translated_synonym_relations-label-synonym_relation_id-51: akceptita
  translated_synonym_relations-label-synonym_relation_id-52: autoritato
  translated_synonym_relations-label-synonym_relation_id-54: subjektiva sinonimo
  translated_synonym_relations-label-synonym_relation_id-56: erara literumo
  translated_synonym_relations-label-synonym_relation_id-57: alternativo literuma
  translated_synonym_relations-label-synonym_relation_id-58: leksika varianto
  translated_synonym_relations-label-synonym_relation_id-59: sinonimo (objektiva = homotipa)
  translated_synonym_relations-label-synonym_relation_id-60: sinonimo (subjektiva = heterotipa)
  translated_synonym_relations-label-synonym_relation_id-61: objektiva sinonimo
  translated_synonym_relations-label-synonym_relation_id-63: neakceptita
  translated_synonym_relations-label-synonym_relation_id-64: nevalida
  translated_synonym_relations-label-synonym_relation_id-65: genra sinonimo
  translated_synonym_relations-label-synonym_relation_id-67: specio prienketenda
  translated_synonym_relations-label-synonym_relation_id-68: hortikultura
  translated_table_of_contents-label-table_of_contents_id-1: Superrigardo
  translated_table_of_contents-label-table_of_contents_id-14: IUCN
  translated_table_of_contents-label-table_of_contents_id-194: Grandeco
  translated_table_of_contents-label-table_of_contents_id-221: Riskoj
  translated_table_of_contents-label-table_of_contents_id-24: Komentaro
  translated_table_of_contents-label-table_of_contents_id-267: Morfologio
  translated_table_of_contents-label-table_of_contents_id-278: Bibliografio
  translated_table_of_contents-label-table_of_contents_id-285: Asociiĝoj
  translated_table_of_contents-label-table_of_contents_id-289: Evoluo
  translated_table_of_contents-label-table_of_contents_id-292: Similŝajnaĵoj
  translated_table_of_contents-label-table_of_contents_id-299: Edukado
  translated_table_of_contents-label-table_of_contents_id-3: Fizika priskribo
  translated_table_of_contents-label-table_of_contents_id-300: Vikipedio
  translated_table_of_contents-label-table_of_contents_id-303: Nomoj kaj taksonomio
  translated_table_of_contents-label-table_of_contents_id-305: Sinonimoj
  translated_table_of_contents-label-table_of_contents_id-306: Paĝa statistiko
  translated_table_of_contents-label-table_of_contents_id-308: Ampleksa priskribo
  translated_table_of_contents-label-table_of_contents_id-309: Distribuo
  translated_table_of_contents-label-table_of_contents_id-310: Disvolviĝo
  translated_table_of_contents-label-table_of_contents_id-312: Migrado
  translated_table_of_contents-label-table_of_contents_id-315: Vivhistorio kaj konduto
  translated_table_of_contents-label-table_of_contents_id-316: Konduto
  translated_table_of_contents-label-table_of_contents_id-318: Vivciklo
  translated_table_of_contents-label-table_of_contents_id-319: Vivekspekto
  translated_table_of_contents-label-table_of_contents_id-320: Reprodukto
  translated_table_of_contents-label-table_of_contents_id-321: Kreskado
  translated_table_of_contents-label-table_of_contents_id-322: Fosilia historio
  translated_table_of_contents-label-table_of_contents_id-324: Funkciaj adaptaĵoj
  translated_table_of_contents-label-table_of_contents_id-325: Fiziologio kaj ĉelbiologio
  translated_table_of_contents-label-table_of_contents_id-326: Molekula biologio kaj genetiko
  translated_table_of_contents-label-table_of_contents_id-327: Fiziologio
  translated_table_of_contents-label-table_of_contents_id-328: Ĉelbiologio
  translated_table_of_contents-label-table_of_contents_id-329: Genetiko
  translated_table_of_contents-label-table_of_contents_id-33: Tendencoj
  translated_table_of_contents-label-table_of_contents_id-330: Nukleotidaj sekvencoj
  translated_table_of_contents-label-table_of_contents_id-331: Strikodo
  translated_table_of_contents-label-table_of_contents_id-332: Genomo
  translated_table_of_contents-label-table_of_contents_id-333: Molekula biologio
  translated_table_of_contents-label-table_of_contents_id-334: Minacoj
  translated_table_of_contents-label-table_of_contents_id-335: Leĝdonaĵo
  translated_table_of_contents-label-table_of_contents_id-336: Notoj
  translated_table_of_contents-label-table_of_contents_id-337: Edukado
  translated_table_of_contents-label-table_of_contents_id-338: Ligiloj pri edukado
  translated_table_of_contents-label-table_of_contents_id-339: Rimedoj pri edukado
  translated_table_of_contents-label-table_of_contents_id-34: Komentoj
  translated_table_of_contents-label-table_of_contents_id-341: Scienco far civitanoj
  translated_table_of_contents-label-table_of_contents_id-342: Ligiloj pri scienco far civitanoj
  translated_table_of_contents-label-table_of_contents_id-344: Dateno
  translated_table_of_contents-label-table_of_contents_id-345: Datenofontoj
  translated_table_of_contents-label-table_of_contents_id-346: Biomedicinaj terminoj
  translated_table_of_contents-label-table_of_contents_id-347: Taksonomio
  translated_table_of_contents-label-table_of_contents_id-348: Informo pri tipo
  translated_table_of_contents-label-table_of_contents_id-4: Ekologio
  translated_table_of_contents-label-table_of_contents_id-41: Habitatloko
  translated_table_of_contents-label-table_of_contents_id-8: Konservado
  translated_untrust_reasons-label-untrust_reason_id-1: misidentiga
  translated_untrust_reasons-label-untrust_reason_id-2: malĝusta/miskonduka
  translated_untrust_reasons-label-untrust_reason_id-3: malalta kvalito
  translated_untrust_reasons-label-untrust_reason_id-4: duoblaĵo
  translated_untrust_reasons-label-untrust_reason_id-5: Alia
  translated_user_identities-label-user_identity_id-1: entuziasmulo
  translated_user_identities-label-user_identity_id-2: studento
  translated_user_identities-label-user_identity_id-3: edukisto
  translated_user_identities-label-user_identity_id-4: civitana sciencisto
  translated_user_identities-label-user_identity_id-5: profesia sciencisto
  translated_vetted-label-vetted_id-0: Nekonata
  translated_vetted-label-vetted_id-4: Nefidata
  translated_vetted-label-vetted_id-5: Fidata
  translated_vetted-label-vetted_id-6: Netaŭga
  translated_view_styles-name-view_style_id-1: Listo
  translated_view_styles-name-view_style_id-2: Galerio
  translated_visibilities-label-visibility_id-0: Nevidebla
  translated_visibilities-label-visibility_id-1: Videbla
