# Messages for Ingush (ГІалгІай Ğalğaj)
# Exported from translatewiki.net
# Export driver: syck-pecl
# Author: Amire80
# Author: Sapral Mikail
# Author: Tagir
inh: 
  all_pages: Еррига оагӀувнаш
  cancel: Юхадаккха
  collections: Гуламаш
  go: Кхоачашде
  help: Новкъoстал
  home: ЦIа
  images: Исбахьалсурташ
  language: "Мотт:"
  leave_a_comment: Дош ала
  login: чувала/яла
  login_or_create_account: Чувала/яла е керда цIи хьакхолла
  logout: Аравала/яла
  my_info: Са хоам
  punctuation_comma: ","
  rights: Бокъо
  show_status_message: Соакхал хьахьокха
  unreviewed: Ца хьажараш
