# Messages for Kurdish (Latin script) (‪Kurdî (latînî)‬)
# Exported from translatewiki.net
# Export driver: syck-pecl
# Author: George Animal
ku-latn: 
  all_pages: Hemû rûpel
  detail: Detay
  help: Alîkarî
  image_not_found: Wêne nehate dîtin
  images: Wêne
  rights: Maf
  unknown: Nenas
