# Messages for Cornish (Kernowek)
# Exported from translatewiki.net
# Export driver: syck-pecl
# Author: Kw-Moon
kw: 
  admin: menystrer
  help: Gweres
  home: Tre
  images: Imajys
  license: Cubmyas
  location: Desedhans
  media: Media
  my_info: Ow hedhlow
  twitter: Twitter
  what_is_this_question: Pandr'ew hebma?
