# Messages for Lithuanian (Lietuvių)
# Exported from translatewiki.net
# Export driver: syck-pecl
# Author: Eitvys200
lt: 
  account_information: Sąskaitos informacija
  account_registered_but_not_ready_try_later: Jūsų sąskaita yra registruota, tačiau nėra pasiruošusi jūsų prieigai. Bandykite dar kartą po penkių minučių.
  add_to_my_collection_button: Pridėti į mano kolekciją
  admin: administratorius
  already_a_member_question: Jau narys?
  cancel: Atšaukti
  collections: Kolekcijos
  content_summary_table_count_column_header: Skaičiuoti
  donate: Aukoti
  edit_community: Redaguoti bendruomenę
  edit_my_profile: Redaguoti mano profilį
  eol_news: EOL Naujienos
  explore: Naršyti
  filter_by_status_all_option: visos būsenos
  filter_by_status_untrusted_option: nepatikimas
  filter_by_type_all_option: visų tipų
  go: Pirmyn
  help: Pagalba
  home: Pradžia
  image_is_no_longer_available: Vaizdas nebegaliojantis
  image_not_found: Vaizdas nerastas
  images: Paveikslėliai
  last_updated_time_ago: Atnaujinta %{time_passed} atgal
  license: Licencija
  location: Vietovė
  media: Žiniasklaida
  must_be_less_than_128_characters_long: turi būti mažesnis nei 128 simbolių.
  my_activity: Mano veikla
  my_info: Mano informacija
  pages_with_pictures_and_text: Puslapių su paveikslėliais ir tekstu
  personal_space: Asmeninė erdvė
  punctuation_comma: ","
  remove_membership: Pašalinti narystę
  resources: Ištekliai
  rights: Teisės
  rights_holder: Teisių turėtojas
  search_placeholder: Ieškoti EOL ...
  show_status_message: Rodyti būsenos pranešimą
  show_warning_message: Šou įspėjamąjį pranešimą
  sign_in: Registruotis
  source_url: Šaltinio URL
  twitter: Twitter
  unknown: Nežinoma
  what_is_eol: Kas yra EOL?
  what_is_this_question: Kas tai?
  you_are_not_authorized_to_perform_this_action: Jums neleidžiama atlikti šį veiksmą.
  you_left_community: Jūs sėkmingai palikote šia bendruomenę.
  your_rating: Jūsų vertinimas
