# Messages for Pashto (پښتو)
# Exported from translatewiki.net
# Export driver: syck-pecl
# Author: Ahmed-Najib-Biabani-Ibrahimkhel
ps: 
  account_information: د ګڼون مالومات
  activerecord: 
    attributes: 
      data_object: 
        object_title: سرليک
      name: 
        string: نوم
      translated_content_page: 
        main_content: جوسه
        title: سرليک
      user: 
        bio: ژونليک
        entered_password: پټنوم
        family_name: وروستی نوم
        full_name: بشپړ نوم
        given_name: لومړی نوم
        username: کارن-نوم
    models: 
      user: ګڼون
  add_language: ژبه ورګډول
  add_page: مخ ورګډول
  admin: پازوال
  admin_translated_content_page_new_link: ژباړه ورګډول
  agent: پلاوی
  all: ټول
  all_articles: ټولې ليکنې
  all_changes: ټول بدلونونه
  all_images: ټول انځورونه
  all_pages: ټول مخونه
  all_people: ټول خلک
  all_sounds: ټول غږونه
  all_title: ټول
  all_videos: ټولې ويډيوګانې
  already_a_member_question: آيا د پخوا نه غړيتوب لرۍ؟
  and: او
  and_between_form_items: او
  assistive_maps_header: نخشې
  assistive_media_header: رسنۍ
  assistive_names_synonyms_header: هممانيزونه
  assistive_taxon_community_header: ټولنه
  associated_with_image_header: پدې انځور کې
  associated_with_video_header: پدې ويډيو کې
  audio_mute: ټپول
  audio_play: غږول
  audio_stop: درول
  cancel: ناګارل
  change: بدلول
  content_partner_resource_auto_publish_false: نه
  content_partner_resource_auto_publish_true: هو
  content_partner_resource_edit_link: سمول
  content_partner_resource_hierarchy_edit_link: سمول
  content_partner_resource_resource_status_new: جوړ شو
  content_partner_resource_vetted_false: نه
  content_partner_resource_vetted_true: هو
  content_partner_resource_view_link: کتل
  content_partner_statistics_year_label: کال
  content_summary_table_count_column_header: شمېرل
  delete: ړنګول
  delete_firstcap: ړنګول
  donate: بسپنه ورکول
  edit: سمول
  email: برېښليک
  email_colon: "برېښليک:"
  eol_pages: مخونه
  facebook: فېسبوک
  filter_by_type_user_option: خلک
  filter_by_type_video_option: ويډيوګانې
  go: ورځه
  help: لارښود
  helpers: 
    label: 
      data_object: 
        license_id: منښتليک
      resource: 
        resource_status: دريځ
        resource_status_id: دريځ
      session: 
        password: پټنوم
      user: 
        bio: زما په اړه
        mailing_list_yes: هو
        user_identities: زه يم
    select: 
      prompt: لطفاً وټاکۍ
    submit: 
      content_page: 
        create: مخ جوړول
        edit: سمول
      create: "%{model} جوړول"
      data_object: 
        create: ليکنه ورګډول
        create_text: ليکنه ورګډول
        update: ليکنه خوندي کول
      name: 
        create: نوم ورګډول
        update: نوم اوسمهالول
      session: 
        create: ننوتل
      submit: "%{model} خوندي کول"
      translated_content_page: 
        create: ژباړه ورګډول
        update: د ژباړې بدلونونه خوندي کول
      user: 
        forgot_password: برېښليک لېږل
  home: کور
  images: انځورونه
  language: "ژبه:"
  license: منښتليک
  location: ځای
  login: ننوتل
  login_or_create_account: ننوتل او يا نوی ګڼون جوړول
  logout: وتل
  media: رسنۍ
  my_activity: زما کواندتيا
  my_info: زما مالومات
  names: نومونه
  names_children_column_header: ماشومان
  names_name_column_header: نوم
  names_status_column_header: دريځ
  none: هېڅ
  notes: يادښتونه
  object_status_all_option: ټول
  object_type_all_option: ټول
  object_type_image_option: انځور
  object_type_sound_option: غږ
  object_type_text_option: متن
  object_type_user_option: کارن
  object_type_video_option: ويډيو
  object_visibility_all_option: ټول
  object_visibility_invisible_option: پټ
  object_visibility_visible_option: ښکاره
  pages_admin_section_link: پازوالان
  pages_lowercase: مخونه
  password_colon: "پټنوم:"
  rights: رښتې
  save: خوندي کول
  search: پلټل
  search_lowercase: پلټل
  select_colon: "ټاکل:"
  send_email_colon: برېښليک لېږل
  show: ښکاره کول
  sign_in: ننوتل
  sign_out: وتل
  sort_by_newest_option: تر ټولو نوی
  sort_by_oldest_option: تر ټولو زوړ
  sort_by_status_option: دريځ
  submit: سپارل
  synonym: هممانيز
  text: متن
  text_capital: متن
  unknown: ناجوت
  user: کارن
  username_colon: "کارن-نوم:"
  users_about_me_header: زما په اړه
  view: کتل
  weekly: اونيز
  what_is_this_question: دا څه دی؟
  yes_answer: هو
