# Messages for Albanian (Shqip)
# Exported from translatewiki.net
# Export driver: syck-pecl
# Author: Vinie007
sq:
  account_information: Account Information
  account_registered_but_not_ready_try_later: Llogaria juaj është e regjistruar, por nuk është gati për ju për të hyrë. Ju lutemi provoni përsëri në pesë minuta.
  add_to_my_collection_button: Shto ne mbledhjen e mia
  all_pages: Të gjitha faqet
  already_a_member_question: Already a Member?
  already_member_of_community: Ju jeni tashmë një anëtar i këtij komuniteti.
  application_version_advisory_information: version Aplikimi
  are_you_sure: A jeni i sigurt?
  cannot_be_associated_with_both_a_user_and_a_community: Mund të mos jetë i lidhur me dy user një dhe një komunitet
  cannot_be_empty: nuk mund të jetë bosh.
  citation: Citim
  classifications_summary_header_with_count:
    one: Part of %{count} approved classification
    other: Part of %{count} approved classifications
  collections: Koleksioni
  collections_summary_header_with_count:
    one: Present in %{count} collection
    other: Present in %{count} collections
  collections_with_count:
    one: "%{count} Collection"
    other: "%{count} Collections"
  common_names_with_count:
    one: "%{count} common name"
    other: "%{count} common names"
  communities: Komuniteteve
  communities_summary_header_with_count:
    one: Belongs to %{count} community
    other: Belongs to %{count} communities
  communities_with_count:
    one: "%{count} Community"
    other: "%{count} Communities"
  community: Komunitetit
  community_activity: Aktivizimi i komunitetit
  community_focus: fokus Komuniteti
  community_members: Anëtarët e Komunitetit
  contact_us_link: Na kontaktoni
  content_partners: Partneret Përmbajtja
  could_not_find_user: Nuk mund të gjejnë një anëtar për këtë përdorues
  create_a_collection: Krijo një koleksion
  create_a_community: Krijo një komunitet
  created_community: Komuniteti u krijuar me sukses.
  curators_summary_header_with_count:
    one: "%{count} Curator"
    other: "%{count} Curators"
  currently_in_eol: Aktualisht në Encyclopedia of Life
  delete_community: Fshije kete komunitet
  detail: Hollësi
  development_version_name: V2 ZHVILLIMIT VERSION - jo për përdorim publik
  donate: Dhurime
  donation_error_no_amount: Ju lutem zgjidhni një sasi donacion.
  donation_error_only_numbers: Ju lutem shkruani një sasi të përdorur vetëm numra.
  edit_community: Edit komunitetin
  encyclopedia_of_life: Enciklopedia e jetës
  endorsed_collections: koleksione Miratohet
  eol_glossary: EOL Fjalor
  eol_news: EOL Lajme
  explore: Eksploro
  global_access_tagline: Global qasje në njohuri në lidhje me jetën në Tokë.
  global_navigation: Global Navigation
  go: Shko
  has_already_been_taken: tashmë është marrë.
  help: Ndihmë
  home_page_link_advisory_information: Kjo lidhje do të keni në faqen kryesore të Enciklopedisë Of Life Web site
  image_is_no_longer_available: Image nuk është më në dispozicion
  image_not_found: Image nuk u gjet
  images: Imazhi
  images_with_count:
    one: "%{count} image"
    other: "%{count} images"
  indexed: Indexed
  iucn_red_list_status_advisory_information: Kjo lidhje do të keni për të Bashkimit Ndërkombëtar për Ruajtjen e Natyrës (IUCN) Web site ku ju mund të gjeni më shumë informacion në Listën e Kuqe e IUCN të specieve të rrezikuara.
  join_community_button: Join ky komunitet
  join_eol_button_html: Eja hajde tek <abbr title="Encyclopedia of Life">EOL</abbr> Tani
  join_eol_community_html: Bëhuni pjesë e komunitetit <abbr title="Enciklopedia e jetës">EOL!</abbr>
  just_pages_with_pictures_and_text: Vetëm ato faqe me fotografi dhe tekst
  learn_about_content_partners: Mësoni rreth përmbajtjes së partnerëve tanë
  license: Liçenca
  login_or_create_account: Hyni ose hapni një llogari
  maps_with_count:
    one: "%{count} Map"
    other: "%{count} Maps"
  media: Media
  media_with_count:
    one: "%{count} Media"
    other: "%{count} Media"
  members_with_count:
    one: "%{count} contributor"
    other: "%{count} contributors"
  minimal_page: Faqe minimale
  must_be_associated_with_either_a_user_or_a_community: Duhet të shoqërohet me një ose përdoruesi ose një komunitet
  must_be_less_than_128_characters_long: duhet të jetë më pak se 128 karaktere.
  must_be_logged_in: Ju duhet të keni hyrë brenda për të kryer këtë veprim.
  newsfeed: Lajme
  not_evaluated: Nuk eshte akoma e vlerësuar
  other_collection_items_with_count:
    one: "%{count} other item"
    other: "%{count} other items"
  other_community_items_with_count:
    one: "%{count} other item"
    other: "%{count} other items"
  overview: Vështrim i Përgjithshëm
  pages_with_pictures_and_text: Faqet me foto ose tekst
  pages_with_pictures_or_text: Faqet me foto ose tekst
  people_with_count:
    one: "%{count} person"
    other: "%{count} people"
  post_comment: Postoje kommentin
  preferred_common_name_advisory_information: Ky është emri i preferuar i përbashkët për këtë takson.
  profile: Profili
  profile_image_alt_text_curator: Profile picture for curator %{user_full_name}
  profile_image_alt_text_member: Profile picture for member %{user_full_name}
  punctuation_comma: ","
  recent_updates: mo te rejat
  remove_membership: Hiq anëtarësimit
  rights: Të drejtave të
  rights_holder: Mbajtës të drejtave të
  search_by_term_page_title: "EOL Search: %{term}"
  search_field_label: Search EOL
  search_input_advisory_information: Enter emra të përbashkët ose shkencor të organizmave të gjallë që do të donit të dini më shumë rreth, për shembull, të përpiqen të hyjnë domate.
  search_placeholder: EOL kerko ...
  search_the_site: Kerko ne Uebsite
  see_all_classifications_with_count_html:
    one: See the <span class="assistive">%{count} approved classification in which this taxon appears.</span>
    other: See all <span class="assistive">%{count} approved classifications in which this taxon appears.</span>
  see_all_collections_with_count_html:
    one: See the <span class="assistive">%{count} collection in which this taxon appears.</span>
    other: See all <span class="assistive">%{count} collections in which this taxon appears.</span>
  see_all_communities_with_count_html:
    one: See the <span class="assistive">%{count} community that focus on this taxon.</span>
    other: See all <span class="assistive">%{count} communities that focus on this taxon.</span>
  see_all_media_link: Shihni të gjitha mediat
  select_topic: Ju lutem zgjidhni një zonë temë
  selected_language_advisory_information: Kjo është gjuha e përzgjedhur për çastin.
  sign_in: Kycu
  sign_out: Dill jasht
  site_information: informacion Site
  skip_to_content: Skip to content
  source_url: "Burimi URL:"
  switch_language_advisory_information: Ndryshuar gjuhën e faqes për language_label {}%
  taxa: Taxa
  taxa_with_count:
    one: "%{count} taxon"
    other: "%{count} taxa"
  taxon: takson
  text_summary_more_link: Read full entry
  there_are_currently_no_members_in_this_community: Aktualisht nuk ka anëtarë në këtë komunitet.
  this_community_has_no_focus_list: Ky komunitet ka asnjë listë fokus.
  threat_status_header_colon: "status Threat:"
  total_items_with_count:
    one: "%{count} item"
    other: "%{count} total items"
  unknown: I panjohur
  updated_community: Komuniteti u freskua me sukses.
  user_comment: Vërejtjet e përdoruesit
  user_system_down: Ne kërkojmë ndjesë, por regjistrimin e përdoruesit sistemi nuk është aktualisht në dispozicion. Ju lutem provoni përsëri më vonë.
  videos_with_count:
    one: "%{count} video"
    other: "%{count} videos"
  view_only_pages_with_at_least_a_picture_or_piece_of_text: Shiko faqet e vetëm me të paktën një foto ose pjesë të tekstit
  what_is_eol: Çfarë është EOL?
  you_are_an_admin_so_i_will_show_you_that_the_error_was: "You are an admin.  So, I will show you that the error was:"
  you_are_not_authorized_to_perform_this_action: Ju nuk jeni i autorizuar për të kryer këtë veprim.
  you_joined_community: Ju keni bashkuar me sukses këtë komunitet.
  you_left_community: Ju jeni larguar me sukses këtë komunitet.
  your_preferences: Preferenca juaj
