# Messages for Telugu (తెలుగు)
# Exported from translatewiki.net
# Export driver: syck-pecl
# Author: Veeven
te: 
  0_1_or_2: 0, 1 లేదా 2
  0_or_1: 0 లేదా 1
  about_eol: EOL గురించి
  account_information: ఖాతా సమాచారం
  action: చర్య
  actions: చర్యలు
  activerecord: 
    attributes: 
      content_partner: 
        display_name: చూపించే పేరు
      data_object: 
        description: వివరణ
        object_title: శీర్షిక
      name: 
        string: పేరు
      translated_content_page: 
        title: శీర్షిక
      user: 
        agreed_with_terms: వాడుక నియమాల ఒప్పందం
        entered_password: సంకేతపదం
        entered_password_confirmation: సంకేతపదం మళ్ళీ <small>(నిర్ధారణకి)</small>
        full_name: పూర్తి పేరు
        language_abbr: ప్రాధాన్యతా భాష
        username: వాడుకరిపేరు
    errors: 
      format: "%{attribute} %{message}"
    models: 
      user: ఖాతా
  admin_content_partners_statistics_link: గణాంకాలు
  admin_link: అవలోకనం
  all_pages: అన్ని పుటలు
  already_a_member_question: ఇప్పటికే సభ్యులా?
  and: మరియు
  and_between_form_items: మరియు
  assistive_details_header: వివరాలు
  assistive_literature_header: సాహిత్యం
  assistive_maps_header: పటములు
  cancel: రద్దుచేయి
  collections: సేకరణలు
  comment: వ్యాఖ్య
  comment_body_label: మీ వ్యాఖ్య
  comments: వ్యాఖ్యలు
  contact_us_link: మమ్మల్ని సంప్రదించండి
  content_partner_agreement_cancel_new_agreement_link: రద్దుచేయి
  content_partner_agreement_cancel_sign_agreement_link: రద్దుచేయి
  content_partner_contacts_header: సంప్రదింపులు
  content_partner_filter_option_vetted_no: కాదు
  content_partner_filter_option_vetted_yes: అవును
  content_partner_public_true: బహిరంగం
  content_partner_resource_auto_publish_false: కాదు
  content_partner_resource_auto_publish_true: అవును
  content_partner_resource_vetted_false: కాదు
  content_partner_resource_vetted_true: అవును
  content_partner_resources_header: వనరులు
  content_partner_statistics_column_header_total_count: అన్ని పేజీలు
  content_partner_statistics_link: వాడుక గణాంకాలు
  content_partner_statistics_month_label: నెల
  content_partner_statistics_year_label: సంవత్సరం
  current_language: "భాష: %{iso_code}"
  daily: ప్రతీరోజూ
  dato_create_cancel: రద్దుచేయి
  dato_edit_cancel: రద్దుచేయి
  delete: తొలగించు
  delete_firstcap: తొలగించు
  description: వివరణ
  details_title: వివరాలు
  encyclopedia_of_life: జీవ విజ్ఞాన సర్వస్వం
  eol_news: EOL వార్తలు
  eol_pages: పుటలు
  error_404_page_title: కనబడలేదు
  example_colon: "ఉదాహరణ:"
  facebook: ఫేస్‌బుక్
  flickr: ఫ్లికర్
  forgot_password_form_cancel: రద్దుచేయి
  go: వెళ్ళు
  go_back: వెనక్కి వెళ్ళండి
  help: సహాయం
  helpers: 
    label: 
      content_partner: 
        logo_current: "ప్రస్తుత చిహ్నం:"
      data_object: 
        object_title: శీర్షిక
      resource: 
        refresh_period_hours: తరచుదనం
        resource_status: స్థితి
        resource_status_id: స్థితి
      session: 
        password: సంకేతపదం
      translated_content_page: 
        language_id: భాష
      user: 
        bio: నా గురించి
        mailing_list_yes: అవును
  home: ముంగిలి
  language: "భాష:"
  language_with_count: "%{language} (%{count})"
  languages: భాషలు
  learn_more_link: (%{learn_more})
  learn_more_lowercase: మరింత తెలుసుకోండి
  license: లైసెన్సు
  literature: సాహిత్యం
  location: ప్రాంతం
  logo_header: చిహ్నం
  maps_with_count: 
    one: "%{count} పటం"
    other: "%{count} పటాలు"
  my_info: నా సమాచారం
  name: పేరు
  names: పేర్లు
  names_name_column_header: పేరు
  names_status_column_header: స్థితి
  object_type_text_option: పాఠ్యం
  object_type_user_option: వాడుకరి
  overview: అవలోకనం
  page_statistics: పుట గణాంకాలు
  pages_lowercase: పేజీలు
  pages_title: పుటలు
  password_colon: "సంకేతపదం:"
  people_with_count: 
    one: "%{count} వ్యక్తి"
    other: "%{count} వ్యక్తులు"
  permalink: స్థిరలంకె
  punctuation_comma: ","
  punctuation_semi_colon: ;
  resources: వనరులు
  rights: హక్కులు
  save: భద్రపరచు
  search: వెతుకు
  show: చూపించు
  site_information: సైటు సమాచారం
  site_language: సైటు భాష
  sort_by_status_option: స్థితి
  statistics: గణాంకాలు
  table_column_header_actions: చర్యలు
  terms_agreement_form_header: వాడుక నియమాలు
  terms_agreement_form_submit: నేను అంగీకరిస్తున్నాను
  text: పాఠ్యం
  text_capital: పాఠ్యం
  thank_you: కృతజ్ఞతలు
  time_ago: "%{time_passed} క్రితం"
  title: శీర్షిక
  twitter: ట్విట్టర్
  type: రకం
  user: వాడుకరి
  user_comment: వాడుకరి వ్యాఖ్య
  username: వాడుకరి పేరు
  username_colon: "వాడుకరి పేరు:"
  users_about_me_header: నా గురించి
  users_form_account_header: మీ ఖాతా
  users_my_info_header: నా సమాచారం
  value: విలువ
  value_default: (అప్రమేయం)
  value_empty: (ఖాళీ)
  values: విలువలు
  video_title_not_available_in_language: శీర్షిక %{language}లో అందుబాటులో లేదు
  web_users: జాల వాడుకరులు
  what_is_eol: EOL అంటే ఏమిటి?
  what_is_this_question: ఇది ఏమిటి?
  will_paginate: 
    page_gap: "&hellip;"
  year: సంవత్సరం
  yes_answer: అవును
  your_preferences: మీ అభిరుచులు
