source 'http://rubygems.org'

group :development, :test do
  gem 'faker'
  gem 'eol_scenarios'
  gem 'rspec', '1.3.0'
  gem 'rspec-rails'
  gem 'factory_girl', '2.0.4'
  gem 'capybara', '0.3.9'
  gem 'daemons'
  gem 'optiflag'
  gem 'ruby-prof'
end

gem 'mysql'
gem 'json', '1.5.3'
gem 'indifferent-variable-hash'
gem 'ruby-debug'
gem 'rails', '2.3.8'
gem 'rack', '1.1.0'
gem 'will_paginate', '2.3.16'
gem 'composite_primary_keys'
gem 'fastercsv'
gem 'haml', '3.1.1'
gem 'macaddr'
gem 'uuid', '2.3.3'
gem 'ezcrypto'
gem 'sanitize','2.0.1'
gem 'escape'
gem 'email_spec', '0.6.2'
gem 'invert'
gem 'sass', '3.1.1'
gem 'newrelic_rpm'
gem 'memcache'
gem 'unicorn', '4.1.1'
gem 'graylog2_exceptions', '1.3.0'
gem 'resque', :require => "resque/server"
