source 'http://rubygems.org'

group :development, :test do
  gem 'faker'
#  gem 'remi-rspec-custom-matchers'
#  gem 'remi-indifferent-variable-hash'
  gem 'eol_scenarios'
  gem 'rspec', '1.3.0'
  gem 'rspec-rails'
  gem 'factory_girl'
  gem 'capybara', '0.3.9'
end

gem 'mysql'
gem 'indifferent-variable-hash'
gem 'ruby-debug'
gem 'rails', '2.3.8'
gem 'rack', '1.1.0'
gem 'will_paginate'
gem 'composite_primary_keys'
gem 'fastercsv'
gem 'haml', '3.1.1'
gem 'macaddr'
gem 'uuid'
gem 'ezcrypto'
gem 'sanitize'
gem 'escape'
gem 'email_spec'
gem 'invert'
gem 'sass', '3.1.1'
