# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require 'rake'
require 'rake/testtask'
# TODO - remove this (and the gem from the Gemfile.) We don't use it.
require 'rake/rdoctask'

require 'tasks/rails'
