class RemoveTaxaTable < ActiveRecord::Migration
  def self.database_model
    return "SpeciesSchemaModel"
  end
  
  def self.up
    # delete orphaned Taxa
    execute('delete t from taxa t left join hierarchy_entries he on (t.hierarchy_entry_id=he.id) where he.id is null')
    
    # Query OK, 12802838 rows affected (17 min 11.03 sec)
    # Query OK, 12802838 rows affected (19 min 3.01 sec)
    # add fields to HierarchyEntries
    execute('alter table hierarchy_entries
            add `guid` varchar(32) character set ascii NOT NULL after `id`,
            add `created_at` timestamp NOT NULL default CURRENT_TIMESTAMP after `visibility_id`,
            add `updated_at` timestamp NOT NULL default "0000-00-00 00:00:00" after `created_at`,
            add `source_url` varchar(255) NOT NULL after `identifier`')
    
    # Query OK, 1600859 rows affected (2 min 40.82 sec)
    # copy data from Taxa to HierarchyEntries
    execute('update ignore taxa t join hierarchy_entries he on (t.hierarchy_entry_id=he.id) set he.guid=t.guid, he.created_at=t.created_at, he.updated_at=t.updated_at')
    
    # Query OK, 1552199 rows affected (3 min 16.69 sec)
    # copy data from ResourcesTaxa to HierarchyEntries
    execute('update ignore resources_taxa rt join taxa t on (rt.taxon_id=t.id) join hierarchy_entries he on (t.hierarchy_entry_id=he.id) set he.source_url=rt.source_url, he.identifier=rt.identifier')
    
    # Query OK, 7779281 rows affected (14 min 51.21 sec)
    # Query OK, 8074798 rows affected (4 min 3.73 sec)
    # change DataObjectsTaxa
    execute('CREATE TABLE `data_objects_hierarchy_entries` (
      `hierarchy_entry_id` int unsigned NOT NULL,
      `data_object_id` int unsigned NOT NULL,
      PRIMARY KEY  (`hierarchy_entry_id`,`data_object_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8')
    SpeciesSchemaModel.connection.begin_db_transaction
    execute('insert ignore into data_objects_hierarchy_entries (select t.hierarchy_entry_id, dot.data_object_id from data_objects_taxa dot join taxa t on (dot.taxon_id=t.id) order by t.id desc)')
    SpeciesSchemaModel.connection.commit_db_transaction
    execute('create index data_object_id on data_objects_hierarchy_entries(data_object_id)')
    drop_table :data_objects_taxa
    
    # change HarvestEventsTaxa
    execute('CREATE TABLE `harvest_events_hierarchy_entries` (
      `harvest_event_id` int unsigned NOT NULL,
      `hierarchy_entry_id` int unsigned NOT NULL,
      `guid` varchar(32) character set ascii NOT NULL,
      `status_id` tinyint unsigned NOT NULL,
      PRIMARY KEY  (`harvest_event_id`,`hierarchy_entry_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8')
    SpeciesSchemaModel.connection.begin_db_transaction
    execute('insert ignore into harvest_events_hierarchy_entries (select het.harvest_event_id, t.hierarchy_entry_id, het.guid, het.status_id from harvest_events_taxa het join taxa t on (het.taxon_id=t.id) order by t.id desc)')
    SpeciesSchemaModel.connection.commit_db_transaction
    execute('create index hierarchy_entry_id on harvest_events_hierarchy_entries(hierarchy_entry_id)')
    execute('create index guid on harvest_events_hierarchy_entries(guid)')
    drop_table :harvest_events_taxa
    
    # change RefsTaxa
    execute('CREATE TABLE `hierarchy_entries_refs` (
      `hierarchy_entry_id` int unsigned NOT NULL,
      `ref_id` int unsigned NOT NULL,
      PRIMARY KEY  (`hierarchy_entry_id`,`ref_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8')
    SpeciesSchemaModel.connection.begin_db_transaction
    execute('insert ignore into hierarchy_entries_refs (select t.hierarchy_entry_id, rt.ref_id from refs_taxa rt join taxa t on (rt.taxon_id=t.id) order by t.id desc)')
    SpeciesSchemaModel.connection.commit_db_transaction
    drop_table :refs_taxa
    
    drop_table :taxa
    drop_table :resources_taxa
    drop_table :common_names
    drop_table :common_names_taxa
  end
  
  def self.down
    drop_table :hierarchy_entries_refs
    drop_table :harvest_events_hierarchy_entries
    drop_table :data_objects_hierarchy_entries
    
    execute("CREATE TABLE `taxa` (
      `id` int(10) unsigned NOT NULL auto_increment,
      `guid` varchar(32) character set ascii NOT NULL COMMENT 'this guid is generated by EOL. A 32 character hexadecimal',
      `taxon_kingdom` varchar(255) NOT NULL,
      `taxon_phylum` varchar(255) NOT NULL,
      `taxon_class` varchar(255) NOT NULL,
      `taxon_order` varchar(255) NOT NULL,
      `taxon_family` varchar(255) NOT NULL,
      `scientific_name` varchar(255) NOT NULL,
      `name_id` int(10) unsigned NOT NULL COMMENT 'the id of the string corresponding with this taxons scientific name. If the scientific name of this taxon doesnt exist one will be created',
      `hierarchy_entry_id` int(10) unsigned NOT NULL COMMENT 'each taxon in this table will be associated with a hierarchy entry created specifically for the associated resource',
      `created_at` timestamp NOT NULL default CURRENT_TIMESTAMP,
      `updated_at` timestamp NOT NULL default '0000-00-00 00:00:00',
      PRIMARY KEY  (`id`),
      KEY `name_id` (`name_id`),
      KEY `index_taxa_on_hierarchy_entry_id` (`hierarchy_entry_id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=utf8 COMMENT='For taxa definitions coming from content partners resources'")
    
    execute("CREATE TABLE `resources_taxa` (
      `resource_id` int(10) unsigned NOT NULL,
      `taxon_id` int(10) unsigned NOT NULL,
      `identifier` varchar(255) NOT NULL,
      `source_url` varchar(255) NOT NULL,
      `taxon_created_at` timestamp NOT NULL default '0000-00-00 00:00:00',
      `taxon_modified_at` timestamp NOT NULL default '0000-00-00 00:00:00',
      PRIMARY KEY  (`resource_id`,`taxon_id`),
      KEY `identifier` (`identifier`),
      KEY `taxon_id` (`taxon_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Perhaps is obsolete now that we have harvest_events and harv'")
    
    execute("CREATE TABLE `common_names` (
      `id` int(10) unsigned NOT NULL auto_increment,
      `common_name` varchar(255) NOT NULL,
      `language_id` smallint(5) unsigned NOT NULL,
      PRIMARY KEY  (`id`),
      KEY `common_name` (`common_name`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Used only to cache common names supplied by content partners'")
    
    execute("CREATE TABLE `common_names_taxa` (
      `taxon_id` int(10) unsigned NOT NULL,
      `common_name_id` int(10) unsigned NOT NULL,
      PRIMARY KEY  (`taxon_id`,`common_name_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='links a resources common names with its taxa'")
    
    execute('CREATE TABLE `data_objects_taxa` (
      `taxon_id` int(10) unsigned NOT NULL,
      `data_object_id` int(10) unsigned NOT NULL,
      `identifier` varchar(255) NOT NULL,
      PRIMARY KEY  (`taxon_id`,`data_object_id`),
      KEY `data_object_id` (`data_object_id`),
      KEY `identifier` (`identifier`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8')
    
    execute('CREATE TABLE `refs_taxa` (
      `taxon_id` int(10) unsigned NOT NULL,
      `ref_id` int(10) unsigned NOT NULL,
      PRIMARY KEY  (`taxon_id`,`ref_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8')
    
    execute('CREATE TABLE `harvest_events_taxa` (
      `harvest_event_id` int(10) unsigned NOT NULL,
      `taxon_id` int(10) unsigned NOT NULL,
      `guid` varchar(32) character set ascii NOT NULL,
      `status_id` tinyint(3) unsigned NOT NULL,
      PRIMARY KEY  (`harvest_event_id`,`taxon_id`),
      KEY `taxon_id` (`taxon_id`),
      KEY `guid` (`guid`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8')
    
    remove_column :hierarchy_entries, :guid
    remove_column :hierarchy_entries, :created_at
    remove_column :hierarchy_entries, :updated_at
    remove_column :hierarchy_entries, :source_url
  end
end
