class CreateTaxonConceptMetrics < EOL::DataMigration
  def self.up
    execute("CREATE TABLE `taxon_concept_metrics` (
          `taxon_concept_id` int(11) DEFAULT NULL,
          `image_total` mediumint(9) DEFAULT NULL,
          `image_trusted` mediumint(9) DEFAULT NULL,
          `image_untrusted` mediumint(9) DEFAULT NULL,
          `image_unreviewed` mediumint(9) DEFAULT NULL,
          `image_total_words` mediumint(9) DEFAULT NULL,
          `image_trusted_words` mediumint(9) DEFAULT NULL,
          `image_untrusted_words` mediumint(9) DEFAULT NULL,
          `image_unreviewed_words` mediumint(9) DEFAULT NULL,
          `text_total` mediumint(9) DEFAULT NULL,
          `text_trusted` mediumint(9) DEFAULT NULL,
          `text_untrusted` mediumint(9) DEFAULT NULL,
          `text_unreviewed` mediumint(9) DEFAULT NULL,
          `text_total_words` mediumint(9) DEFAULT NULL,
          `text_trusted_words` mediumint(9) DEFAULT NULL,
          `text_untrusted_words` mediumint(9) DEFAULT NULL,
          `text_unreviewed_words` mediumint(9) DEFAULT NULL,
          `video_total` mediumint(9) DEFAULT NULL,
          `video_trusted` mediumint(9) DEFAULT NULL,
          `video_untrusted` mediumint(9) DEFAULT NULL,
          `video_unreviewed` mediumint(9) DEFAULT NULL,
          `video_total_words` mediumint(9) DEFAULT NULL,
          `video_trusted_words` mediumint(9) DEFAULT NULL,
          `video_untrusted_words` mediumint(9) DEFAULT NULL,
          `video_unreviewed_words` mediumint(9) DEFAULT NULL,
          `sound_total` mediumint(9) DEFAULT NULL,
          `sound_trusted` mediumint(9) DEFAULT NULL,
          `sound_untrusted` mediumint(9) DEFAULT NULL,
          `sound_unreviewed` mediumint(9) DEFAULT NULL,
          `sound_total_words` mediumint(9) DEFAULT NULL,
          `sound_trusted_words` mediumint(9) DEFAULT NULL,
          `sound_untrusted_words` mediumint(9) DEFAULT NULL,
          `sound_unreviewed_words` mediumint(9) DEFAULT NULL,
          `flash_total` mediumint(9) DEFAULT NULL,
          `flash_trusted` mediumint(9) DEFAULT NULL,
          `flash_untrusted` mediumint(9) DEFAULT NULL,
          `flash_unreviewed` mediumint(9) DEFAULT NULL,
          `flash_total_words` mediumint(9) DEFAULT NULL,
          `flash_trusted_words` mediumint(9) DEFAULT NULL,
          `flash_untrusted_words` mediumint(9) DEFAULT NULL,
          `flash_unreviewed_words` mediumint(9) DEFAULT NULL,
          `youtube_total` mediumint(9) DEFAULT NULL,
          `youtube_trusted` mediumint(9) DEFAULT NULL,
          `youtube_untrusted` mediumint(9) DEFAULT NULL,
          `youtube_unreviewed` mediumint(9) DEFAULT NULL,
          `youtube_total_words` mediumint(9) DEFAULT NULL,
          `youtube_trusted_words` mediumint(9) DEFAULT NULL,
          `youtube_untrusted_words` mediumint(9) DEFAULT NULL,
          `youtube_unreviewed_words` mediumint(9) DEFAULT NULL,
          `iucn_total` tinyint(3) DEFAULT NULL,
          `iucn_trusted` tinyint(3) DEFAULT NULL,
          `iucn_untrusted` tinyint(3) DEFAULT NULL,
          `iucn_unreviewed` tinyint(3) DEFAULT NULL,
          `iucn_total_words` tinyint(3) DEFAULT NULL,
          `iucn_trusted_words` tinyint(3) DEFAULT NULL,
          `iucn_untrusted_words` tinyint(3) DEFAULT NULL,
          `iucn_unreviewed_words` tinyint(3) DEFAULT NULL,
          `data_object_references` smallint(6) DEFAULT NULL,
          `info_items` smallint(6) DEFAULT NULL,
          `BHL_publications` smallint(6) DEFAULT NULL,
          `content_partners` smallint(6) DEFAULT NULL,
          `outlinks` smallint(6) DEFAULT NULL,
          `has_GBIF_map` tinyint(1) DEFAULT NULL,
          `has_biomedical_terms` tinyint(1) DEFAULT NULL,
          `user_submitted_text` smallint(6) DEFAULT NULL,
          `submitted_text_providers` smallint(6) DEFAULT NULL,
          `common_names` smallint(6) DEFAULT NULL,
          `common_name_providers` smallint(6) DEFAULT NULL,
          `synonyms` smallint(6) DEFAULT NULL,
          `synonym_providers` smallint(6) DEFAULT NULL,
          `page_views` mediumint(9) DEFAULT NULL,
          `unique_page_views` mediumint(9) DEFAULT NULL
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8")
  end

  def self.down
    drop_table :taxon_concept_metrics
  end
end


