#! /usr/bin/env ruby
require File.dirname(__FILE__) + '/api'
require 'irb'

puts %{
  Welcome to the EOL API console

  Currently, this assumes that you have the EOL website 
  running locally at http://localhost:3000

  Example Usage:
    >> tigers = Species.search('tiger')
    >> a_tiger = Species.search('tiger').first
    >> images_of_a_tiger = a_tiger.images
    >> image_urls = images_of_a_tiger.map &:url
    >> Species.search('walter').first.images.map &:url
    >> Species.random

}

include EOL::API

IRB.start
